#!/bin/bash
set -o nounset
set -o errexit

if [[ ${1:-} ]]; then
  case ${1} in
  # If the verb "PRE" is passed as the first parameter, then determine
  # if "COMMAND_PRE" is defined. Execute "COMMAND_PRE" and return the
  # exit status to the parent process.
  'pre') 
    if [[ ${COMMAND_PRE:-} ]]; then
      eval "${COMMAND_PRE}"
      exit $?
    fi
    ;;

  # If the verb "POST" is passed as the first parameter, then determine
  # if "COMMAND_POST" is defined. Execute "COMMAND_POST" and return the
  # exit status to the parent process.
  'post')
    if [[ ${COMMAND_POST:-} ]]; then
      eval "${COMMAND_POST}"
      exit $?
    fi
    ;;
  esac
  exit 0
fi

exec ssh \
  -N `# no stdin` \
  -T `# no psuedo-terminal` \
  -n `# no remote command` \
  -o ServerAliveCountMax=3  `# number of server queries` \
  -o ServerAliveInterval=10 `# seconds between server queries` \
  ${SSH_OPTIONS[@]} -L ${LOCAL_ADDR}:${LOCAL_PORT}:${REMOTE_ADDR}:${REMOTE_PORT} ${REMOTE_USER}@${REMOTE_HOST}
